version: '3'
services:
  web:
    platform: linux/amd64
    image: nginx:1.21
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html