version: '3'
services:
  nginx:
    depends_on:
      - app
    platform: linux/amd64
    image: nginx:1.15
    ports:
      - 80:80
    volumes:
      - ./src/html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  app:
    depends_on:
      - mysql
    platform: linux/amd64
    build: ./php-fpm
    volumes:
      - ./src/html:/var/www/html
  mysql:
    platform: linux/amd64
    build: ./mysql
    environment:
      MYSQL_DATABASE: posse
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: minori
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf